### ISSUE TITLE
Pretrained models are not downloading

### ISSUE THREAD

**Issue by hardikdava** [AyushExel/trolo#16]
Script to reproduce bug

```
from trolo.inference import DetectionPredictor
from PIL import Image

image = Image.open("bus.jpg")

predictor = DetectionPredictor(model="dfine-n") # load model
predictions = predictor.predict(inputs=[image]) # get predictions
poltted_preds = predictor.visualize(input=image, show=True, save=True)# or get visualized outputs
```

traceback:
```
/home/hd/Desktop/python_workspace/trolo/venv/bin/python /home/hd/Desktop/python_workspace/trolo/main.py 
Traceback (most recent call last):
  File "/home/hd/Desktop/python_workspace/trolo/main.py", line 6, in <module>
    predictor = DetectionPredictor(model="dfine-n") # load model
  File "/home/hd/Desktop/python_workspace/trolo/trolo/inference/detection.py", line 41, in __init__
    checkpoint = torch.load(model, map_location="cpu", weights_only=False)
  File "/home/hd/Desktop/python_workspace/trolo/venv/lib/python3.10/site-packages/torch/serialization.py", line 986, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/hd/Desktop/python_workspace/trolo/venv/lib/python3.10/site-packages/torch/serialization.py", line 435, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/hd/Desktop/python_workspace/trolo/venv/lib/python3.10/site-packages/torch/serialization.py", line 416, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/home/hd/Desktop/python_workspace/trolo/trolo/configs/yaml/dfine/dfine_hgnetv2_n_coco.yml'
Warning: Model path dfine-n does not exist, inferring config from model name

Process finished with exit code 1

```

**Comment by hardikdava** [comment]
@AyushExel Seems fixed now. Event cli version is also working.
